"""Congig module with constants."""
DIGIT_PLACES = 2
MONEY_MAX_DIGITS = 8
MINLENGTHVALIDATOR = 12
MAXLENGTHVALIDATOR = 19


PASSWORD1 = 'password1'
PASSWORD2 = 'password2'
NUMBER = 'number'
INVALID = 'invalid'
EXPIRY = 'expiry'
CODE = 'code'
OFF = 'off'


TEST_PASSWORD = 'abcaas'
TEST_USERNAME = 'user'
TEST_SUPERUSERPASSWORD = 'admin'
POINT_SEVEN = 0.7
ELEVEN = 11
TWELVE = 12
FIFTEEN = 15
SIXTEEN = 16
TWENTY_THREE = 23
TWENTY_EIGTH = 28
TWENTY_NINE = 29
PRE_LAST_DAY = 30
DAY_LAST = 31
FIFTY_NINE = 59
YEAR_TWENTY_TWELVE = 2012
YEAR_TWENTY_FIFTEEN = 2015
YEAR_TWENTY_SIXTEEN = 2016
YEAR_TWENTY_EIGHTEEN = 2018
YEAR_TWENTY_TWO = 2022
YEAR_TWENTY_FIVE = 2025
YEAR_THITRY = 2030
YEAR_FIFTY = 2050
TEST_YEAR = 1936


NEVER_YEAR = 3000
PAST_YEAR = 2007


ALL = '__all__'
STAGES = 'stages'
FORM = 'form'
POST = 'POST'
