# Generated by Django 5.0.3 on 2024-04-29 21:38

import competitions_app.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100, verbose_name='competition_name')),
                ('competition_start', models.DateField(blank=True, default=competitions_app.models.get_datetime, null=True, verbose_name='competition_start')),
                ('competition_end', models.DateField(blank=True, default=competitions_app.models.get_datetime, null=True, verbose_name='competition_end')),
            ],
            options={
                'verbose_name': 'Competition',
                'verbose_name_plural': 'Competitions',
                'db_table': '"competitions"."competition"',
                'ordering': ['name', 'competition_start', 'competition_end'],
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100, verbose_name='competition_name')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Sport',
                'verbose_name_plural': 'Sports',
                'db_table': '"competitions"."sport"',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100, verbose_name='competition_name')),
                ('stage_date', models.DateField(blank=True, default=competitions_app.models.get_datetime, null=True, verbose_name='stage_date')),
                ('place', models.TextField(blank=True, max_length=150, null=True, verbose_name='place')),
                ('competition_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions_app.competition', verbose_name='competition_id')),
                ('sport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions_app.sport', verbose_name='sport_id')),
            ],
            options={
                'verbose_name': 'Stage',
                'verbose_name_plural': 'Stages',
                'db_table': '"competitions"."stage"',
                'ordering': ['name', 'stage_date'],
            },
        ),
    ]
