# Generated by Django 5.0.3 on 2024-05-07 03:17

import competitions_app.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, default=competitions_app.models._get_datetime, null=True, validators=[competitions_app.models._check_created], verbose_name='created')),
                ('modified', models.DateTimeField(blank=True, default=competitions_app.models._get_datetime, null=True, validators=[competitions_app.models._check_modified], verbose_name='modified')),
                ('money', models.DecimalField(decimal_places=2, default=0, max_digits=11, validators=[competitions_app.models._check_positive], verbose_name='money')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'db_table': '"crud_api"."client"',
            },
        ),
        migrations.CreateModel(
            name='SportClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, default=competitions_app.models._get_datetime, null=True, validators=[competitions_app.models._check_created], verbose_name='created')),
                ('modified', models.DateTimeField(blank=True, default=competitions_app.models._get_datetime, null=True, validators=[competitions_app.models._check_modified], verbose_name='modified')),
                ('cleint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions_app.client', verbose_name='client')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions_app.sport', verbose_name='sport')),
            ],
            options={
                'verbose_name': 'relationship sport client',
                'verbose_name_plural': 'relationships sport client',
                'db_table': '"crud_api"."sport_client"',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='sports',
            field=models.ManyToManyField(through='competitions_app.SportClient', to='competitions_app.sport', verbose_name='sports'),
        ),
    ]
