# Generated by Django 5.0.3 on 2024-06-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='competition',
            name='check_start_date',
        ),
        migrations.AddConstraint(
            model_name='competition',
            constraint=models.CheckConstraint(check=models.Q(('competition_end__gt', models.F('competition_start'))), name='check_start_date', violation_error_message='Competition cannot end before its start.'),
        ),
    ]
