# Generated by Django 5.0.3 on 2024-04-30 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='competition_id',
        ),
        migrations.AddField(
            model_name='competition',
            name='sports',
            field=models.ManyToManyField(through='competitions_app.CompetitionsSports', to='competitions_app.sport', verbose_name='sports'),
        ),
        migrations.AddField(
            model_name='sport',
            name='competitions',
            field=models.ManyToManyField(through='competitions_app.CompetitionsSports', to='competitions_app.competition', verbose_name='competitions'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='name',
            field=models.TextField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='competitionssports',
            name='competition_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='competitions_app.competition', verbose_name='competition_id'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.TextField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='name',
            field=models.TextField(max_length=100, verbose_name='name'),
        ),
    ]
