# Generated by Django 5.0.3 on 2024-05-07 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions_app', '0002_client_sportclient_client_sports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='comp_sport_id',
            field=models.ForeignKey(db_column='comp_sport_id', on_delete=django.db.models.deletion.CASCADE, to='competitions_app.competitionssports', verbose_name='comp_sport_id'),
        ),
    ]
