# Generated by Django 5.0.3 on 2024-04-30 06:09

import competitions_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions_app', '0003_alter_stage_stage_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='created',
            field=models.DateTimeField(blank=True, default=competitions_app.models.get_datetime, null=True, validators=[competitions_app.models._check_created], verbose_name='created'),
        ),
        migrations.AddField(
            model_name='competition',
            name='modified',
            field=models.DateTimeField(blank=True, default=competitions_app.models.get_datetime, null=True, validators=[competitions_app.models._check_modified], verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='competitionssports',
            name='created',
            field=models.DateTimeField(blank=True, default=competitions_app.models.get_datetime, null=True, validators=[competitions_app.models._check_created], verbose_name='created'),
        ),
        migrations.AddField(
            model_name='competitionssports',
            name='modified',
            field=models.DateTimeField(blank=True, default=competitions_app.models.get_datetime, null=True, validators=[competitions_app.models._check_modified], verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='sport',
            name='created',
            field=models.DateTimeField(blank=True, default=competitions_app.models.get_datetime, null=True, validators=[competitions_app.models._check_created], verbose_name='created'),
        ),
        migrations.AddField(
            model_name='sport',
            name='modified',
            field=models.DateTimeField(blank=True, default=competitions_app.models.get_datetime, null=True, validators=[competitions_app.models._check_modified], verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='stage',
            name='created',
            field=models.DateTimeField(blank=True, default=competitions_app.models.get_datetime, null=True, validators=[competitions_app.models._check_created], verbose_name='created'),
        ),
        migrations.AddField(
            model_name='stage',
            name='modified',
            field=models.DateTimeField(blank=True, default=competitions_app.models.get_datetime, null=True, validators=[competitions_app.models._check_modified], verbose_name='modified'),
        ),
    ]
