name: Checking
on: [push]
jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12
    - name: Download dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8==6.1.0 wemake-python-styleguide==0.18.0 bandit==1.7.5
    - name: Flake8
      run: flake8 .
  tests:
    name: Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
            POSTGRES_DB: crud_hw       
            POSTGRES_PASSWORD: crud_hw
            POSTGRES_USER: crud_hw
            POSTGRES_HOST: 127.0.0.1
        ports:
          - 38700
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10.12"
    - name: Установка модулей и зависимостей
      run: |
        python -m pip install Pillow
        python -m pip install --upgrade pip
        pip install -r tests/requirements.txt
    - name: Тесты models
      run: |
        chmod +x tests/test.sh
        ./tests/test.sh tests.test_models
    - name: Тесты views
      run: |
        chmod +x tests/test.sh
        ./tests/test.sh tests.test_views
    - name: Тесты api
      run: |
        chmod +x tests/test.sh
        ./tests/test.sh tests.test_api
    - name: Тесты forms
      run: |
        chmod +x tests/test.sh
        ./tests/test.sh tests.test_forms
    - name: Тесты profile
      run: |
        chmod +x tests/test.sh
        ./tests/test.sh tests.test_utils
    - name: Тесты add funds
      run: |
        chmod +x tests/test.sh
        ./tests/test.sh tests.test_add_funds