name: Checking
on: [push]
jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12
    - name: Download dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8==6.1.0 wemake-python-styleguide==0.18.0 bandit==1.7.5
    - name: Flake8
      run: flake8 .
  tests:
    name: Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DBNAME: crud_hw       
          POSTGRES_PASSWORD: crud_hw
          POSTGRES_USER: crud_hw
          POSTGRES_HOST: 127.0.0.1
        ports:
          - 38700:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Download Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12
    - name: Download dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Pytest
      run: |
        python3 manage.py test   tests